version: '3.3'
services:
  api-interface:
    image: marketplace_shop_api
    build:
      context: .
    command: php -S 0.0.0.0:8000 -t public/
    volumes:
      - .:/src
      - /src/vendor
    ports:
      - "1004:8000"
    environment:
      - PHP_IDE_CONFIG=serverName=docker

  api-unit-test:
    image: marketplace_shop_api
    command: vendor/bin/phpunit -c tests/phpunit.xml
    environment:
      - APP_ENV=test
      - PHP_IDE_CONFIG=serverName=docker
    env_file:
      - .env
    volumes:
      - .:/src
      - /src/vendor

networks:
  default:
    external:
      name: marketplace-network
